version: '3'
services:
    postgres:
        restart: always
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: password
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
          - sanic

    weather:
        restart: always
        build:
            context: .
        ports:
            - "8000:8000"
        env_file: .env
        volumes:
            - .:/sanic
        environment:
            SANIC_DB_HOST: postgres
            SANIC_DB_PASSWORD: password
            SANIC_DB_DATABASE: postgres
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - sanic
        command: >
          bash -c "python run.py"

volumes:
    pg-data:
        driver: local

networks:
    sanic:
